[build]
  base = "."
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://tfm-1-1sle.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
